"""Added Tab and changed tab field in TodoItem

Revision ID: 2576c97ef866
Revises: db60a7e1b70d
Create Date: 2024-11-10 16:46:09.083011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2576c97ef866'
down_revision = 'db60a7e1b70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###  
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tab_id', 'tab', ['tab_id'], ['id'])  # added a name for the foreign key
        batch_op.drop_column('tab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###  
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_tab_id', type_='foreignkey')  # drop the named foreign key constraint
        batch_op.drop_column('tab_id')

    # ### end Alembic commands ###
