"""Add position column to TodoItem

Revision ID: 8d7f24a6764f
Revises: 
Create Date: 2024-10-03 15:12:14.428657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7f24a6764f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
