"""Added tab field to TodoItem

Revision ID: db60a7e1b70d
Revises: 8d7f24a6764f
Create Date: 2024-11-10 15:34:49.324125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db60a7e1b70d'
down_revision = '8d7f24a6764f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.drop_column('tab')

    # ### end Alembic commands ###
